export const settings = [
	{
		module: "metanthropes",
		key: "metaAdvancedLogging",
		name: "METANTHROPES.SETTINGS.metaAdvancedLoggingName",
		hint: "METANTHROPES.SETTINGS.metaAdvancedLoggingHint",
		scope: "world",
		config: true,
		requiresReload: false,
		type: Boolean,
		default: false,
		onChange: null,
	},
		{
		module: "metanthropes",
		key: "metaNetworkLogging",
		name: "METANTHROPES.SETTINGS.metaNetworkLoggingName",
		hint: "METANTHROPES.SETTINGS.metaNetworkLoggingHint",
		scope: "world",
		config: true,
		requiresReload: false,
		type: Boolean,
		default: false,
		onChange: null,
	},
	{
		module: "metanthropes",
		key: "forceMigration",
		name: "METANTHROPES.SETTINGS.forceMigrationName",
		hint: "METANTHROPES.SETTINGS.forceMigrationHint",
		scope: "world",
		config: true,
		requiresReload: true,
		type: Boolean,
		default: false,
		onChange: null,
	},
	{
		module: "metanthropes",
		key: "metaPause",
		name: "METANTHROPES.SETTINGS.metaPauseName",
		hint: "METANTHROPES.SETTINGS.metaPauseHint",
		scope: "world",
		config: true,
		requiresReload: false,
		type: Boolean,
		default: true,
		onChange: null,
	},
	{
		module: "metanthropes",
		key: "welcomeMsg",
		name: "METANTHROPES.SETTINGS.welcomeMsgName",
		hint: "METANTHROPES.SETTINGS.welcomeMsgHint",
		scope: "world",
		config: true,
		requiresReload: false,
		type: Boolean,
		default: true,
		onChange: null,
	},
	{
		module: "metanthropes",
		key: "dsnDamageDice",
		name: "METANTHROPES.SETTINGS.dsnDamageDiceName",
		hint: "METANTHROPES.SETTINGS.dsnDamageDiceHint",
		scope: "client",
		config: true,
		requiresReload: false,
		type: Boolean,
		default: true,
		onChange: null,
	},
	//! Deprecated
	{
		module: "metanthropes",
		key: "metaWelcome",
		name: "METANTHROPES.SETTINGS.metaWelcomeName",
		hint: "METANTHROPES.SETTINGS.metaWelcomeHint",
		scope: "world",
		config: true,
		requiresReload: false,
		type: Boolean,
		default: false,
		onChange: null,
	},
	{
		module: "metanthropes",
		key: "metaInstall",
		name: "METANTHROPES.SETTINGS.metaInstallName",
		hint: "METANTHROPES.SETTINGS.metaInstallHint",
		scope: "world",
		config: false,
		requiresReload: false,
		type: Boolean,
		default: false,
		onChange: null,
	},
	//* Hidden from the UI
	{
		module: "metanthropes",
		key: "migration",
		name: "Migration Settings",
		hint: ``,
		scope: "world",
		config: false,
		requiresReload: false,
		type: Object,
		default: null,
		onChange: null,
	},
	{
		module: "metanthropes",
		key: "metaDSNSFX",
		name: "Dice So Nice default SFX",
		hint: ``,
		scope: "world",
		config: false,
		requiresReload: false,
		type: Boolean,
		default: false,
		onChange: null,
	},
	//! All below to be Deprecated & moved to their respective modules
	//* Visible with Metanthropes: Introductory
	// {
	// 	module: "metanthropes",
	// 	key: "metaIntroductory",
	// 	name: "Enable Metanthropes: Introductory",
	// 	hint: `
	// 		Makes features included in Metanthropes: Introductory available for the System to use.
	// 		`,
	// 	scope: "world",
	// 	config: false,
	// 	requiresReload: true,
	// 	type: Boolean,
	// 	default: false,
	// 	onChange: null,
	// },
	// //* Visible with Metanthropes: Core
	// {
	// 	module: "metanthropes",
	// 	key: "metaCore",
	// 	name: "Enable Metanthropes: Core",
	// 	hint: `
	// 		Enable this setting to gain access to the Metanthropes: Core features.
	// 		`,
	// 	scope: "world",
	// 	config: false,
	// 	requiresReload: true,
	// 	type: Boolean,
	// 	default: false,
	// 	onChange: null,
	// },
	// {
	// 	module: "metanthropes",
	// 	key: "metaBetaTesting",
	// 	name: "Enable Beta Testing of New Features",
	// 	hint: `
	// 	Enable this setting to test New Features that are still in development.
	// 	These features may not be fully functional and are subject to change during development.
	// 	Make sure you give us your feedback and suggestions!
	// 	`,
	// 	scope: "world",
	// 	config: false,
	// 	requiresReload: true,
	// 	type: Boolean,
	// 	default: false,
	// 	onChange: null,
	// },
	// //* Visible with Metanthropes: Homebrew
	// {
	// 	module: "metanthropes",
	// 	key: "metaHomebrew",
	// 	name: "Enable Metanthropes: Homebrew",
	// 	hint: `
	// 		Enable this setting to gain access to the Metanthropes: Homebrew features.
	// 		`,
	// 	scope: "world",
	// 	config: false,
	// 	requiresReload: true,
	// 	type: Boolean,
	// 	default: false,
	// 	onChange: null,
	// },
	// {
	// 	module: "metanthropes",
	// 	key: "metaAlphaTesting",
	// 	name: "Enable Alpha Testing of Upcoming Features",
	// 	hint: `
	// 	Enable this setting to test Upcoming Features that are still in early development.
	// 	These features are not fully functional and are subject to change during development.
	// 	Make sure you give us your feedback and suggestions!
	// 	`,
	// 	scope: "world",
	// 	config: false,
	// 	requiresReload: true,
	// 	type: Boolean,
	// 	default: false,
	// 	onChange: null,
	// },
	// //* Placeholder for Anthologies
	// {
	// 	module: "metanthropes",
	// 	key: "metaAether",
	// 	name: "Enable Metanthropes: Anthologies - Aether",
	// 	hint: `
	// 		Enable this setting to gain access to the Metanthropes Anthologies: Aether features.
	// 		`,
	// 	scope: "world",
	// 	config: false,
	// 	requiresReload: true,
	// 	type: Boolean,
	// 	default: false,
	// 	onChange: null,
	// },
	// {
	// 	module: "metanthropes",
	// 	key: "metaAstral",
	// 	name: "Enable Metanthropes: Anthologies - Astral",
	// 	hint: `
	// 		Enable this setting to gain access to the Metanthropes Anthologies: Astral features.
	// 		`,
	// 	scope: "world",
	// 	config: false,
	// 	requiresReload: true,
	// 	type: Boolean,
	// 	default: false,
	// 	onChange: null,
	// },
	// {
	// 	module: "metanthropes",
	// 	key: "metaNether",
	// 	name: "Enable Metanthropes: Anthologies - Nether",
	// 	hint: `
	// 		Enable this setting to gain access to the Metanthropes Anthologies: Nether features.
	// 		`,
	// 	scope: "world",
	// 	config: false,
	// 	requiresReload: true,
	// 	type: Boolean,
	// 	default: false,
	// 	onChange: null,
	// },
];
