export const MetapowersList = [
	{ number: 1, name: "6th Sense", classification: "Clairvoyant", energyType: "Psychic", statRolled: "Awareness" },
	{ number: 2, name: "Acidokinesis", classification: "Kineticist", energyType: "Elemental", statRolled: "Power" },
	{ number: 3, name: "Adaptive Imitation", classification: "Aegis", energyType: "Material", statRolled: "Reflexes" },
	{ number: 4, name: "Aerokinesis", classification: "Kineticist", energyType: "Elemental", statRolled: "Reflexes" },
	{
		number: 5,
		name: "Aether Projection",
		classification: "Cosmonaut",
		energyType: "Cosmic",
		statRolled: "Creativity",
	},
	{ number: 6, name: "Alter Energy", classification: "Utilitarian", energyType: "Psychic", statRolled: "Creativity" },
	{ number: 7, name: "Alter Sound", classification: "Utilitarian", energyType: "Elemental", statRolled: "Power" },
	{
		number: 8,
		name: "Ancestral Connection",
		classification: "Utilitarian",
		energyType: "Psychic",
		statRolled: "Consciousness",
	},
	{ number: 9, name: "Animal Powers", classification: "Hammer", energyType: "Elemental", statRolled: "Power" },
	{
		number: 10,
		name: "Animate Objects",
		classification: "Animator",
		energyType: "Psychic",
		statRolled: "Consciousness",
	},
	{
		number: 11,
		name: "Animate Plants",
		classification: "Animator",
		energyType: "Elemental",
		statRolled: "Manipulation",
	},
	{ number: 12, name: "Antikinesis", classification: "Kineticist", energyType: "Cosmic", statRolled: "Power" },
	{
		number: 13,
		name: "Astral Projection",
		classification: "Cosmonaut",
		energyType: "Psychic",
		statRolled: "Consciousness",
	},
	{ number: 14, name: "Atomokinesis", classification: "Kineticist", energyType: "Cosmic", statRolled: "Perception" },
	{ number: 15, name: "Augment Metapower", classification: "Arbiter", energyType: "Cosmic", statRolled: "Awareness" },
	{ number: 16, name: "Biomorphic Powers", classification: "Hammer", energyType: "Material", statRolled: "Power" },
	{ number: 17, name: "Chaos Bending", classification: "Arbiter", energyType: "Cosmic", statRolled: "Consciousness" },
	{
		number: 18,
		name: "Control Dark Matter",
		classification: "Controller",
		energyType: "Cosmic",
		statRolled: "Willpower",
	},
	{
		number: 19,
		name: "Control Density",
		classification: "Controller",
		energyType: "Cosmic",
		statRolled: "Willpower",
	},
	{
		number: 20,
		name: "Control Earth",
		classification: "Controller",
		energyType: "Elemental",
		statRolled: "Willpower",
	},
	{
		number: 21,
		name: "Control Gravity",
		classification: "Controller",
		energyType: "Cosmic",
		statRolled: "Willpower",
	},
	{
		number: 22,
		name: "Control Kinetic Energy",
		classification: "Controller",
		energyType: "Material",
		statRolled: "Willpower",
	},
	{
		number: 23,
		name: "Control Magnetism",
		classification: "Controller",
		energyType: "Cosmic",
		statRolled: "Willpower",
	},
	{
		number: 24,
		name: "Control Matter",
		classification: "Controller",
		energyType: "Material",
		statRolled: "Willpower",
	},
	{
		number: 25,
		name: "Control Weather",
		classification: "Controller",
		energyType: "Elemental",
		statRolled: "Willpower",
	},
	{
		number: 26,
		name: "Craft Disease",
		classification: "Animator",
		energyType: "Elemental",
		statRolled: "Creativity",
	},
	{ number: 27, name: "Craft Toxin", classification: "Animator", energyType: "Elemental", statRolled: "Creativity" },
	{
		number: 28,
		name: "Dark Energy Projection",
		classification: "Cosmonaut",
		energyType: "Cosmic",
		statRolled: "Creativity",
	},
	{
		number: 29,
		name: "Detect Matter",
		classification: "Clairvoyant",
		energyType: "Material",
		statRolled: "Perception",
	},
	{
		number: 30,
		name: "Detect Metapower",
		classification: "Clairvoyant",
		energyType: "Psychic",
		statRolled: "Awareness",
	},
	{
		number: 31,
		name: "Duplicate Object",
		classification: "Animator",
		energyType: "Material",
		statRolled: "Creativity",
	},
	{ number: 32, name: "Duplicate Self", classification: "Animator", energyType: "Material", statRolled: "Endurance" },
	{ number: 33, name: "Elasticity", classification: "Hammer", energyType: "Material", statRolled: "Reflexes" },
	{
		number: 34,
		name: "Electrokinesis",
		classification: "Kineticist",
		energyType: "Elemental",
		statRolled: "Reflexes",
	},
	{ number: 35, name: "Flight", classification: "Cosmonaut", energyType: "Elemental", statRolled: "Reflexes" },
	{
		number: 36,
		name: "Forcefield Generation",
		classification: "Controller",
		energyType: "Material",
		statRolled: "Creativity",
	},
	{ number: 37, name: "Hydrokinesis", classification: "Kineticist", energyType: "Elemental", statRolled: "Reflexes" },
	{
		number: 38,
		name: "Hypnotic Manipulation",
		classification: "Manipulator",
		energyType: "Psychic",
		statRolled: "Manipulation",
	},
	{
		number: 39,
		name: "Illusion Manipulation",
		classification: "Manipulator",
		energyType: "Psychic",
		statRolled: "Manipulation",
	},
	{
		number: 40,
		name: "Immortality",
		classification: "Utilitarian",
		energyType: "Elemental",
		statRolled: "Endurance",
	},
	{
		number: 41,
		name: "Inner Dimension",
		classification: "Cosmonaut",
		energyType: "Cosmic",
		statRolled: "Perception",
	},
	{ number: 42, name: "Intangibility", classification: "Aegis", energyType: "Material", statRolled: "Endurance" },
	{ number: 43, name: "Invisibility", classification: "Aegis", energyType: "Material", statRolled: "Reflexes" },
	{ number: 44, name: "Invulnerability", classification: "Aegis", energyType: "Material", statRolled: "Endurance" },
	{ number: 45, name: "Life Restoration", classification: "Aegis", energyType: "Elemental", statRolled: "Endurance" },
	{
		number: 46,
		name: "Light Projection",
		classification: "Cosmonaut",
		energyType: "Cosmic",
		statRolled: "Perception",
	},
	{ number: 47, name: "Luck Bending", classification: "Arbiter", energyType: "Cosmic", statRolled: "Consciousness" },
	{
		number: 48,
		name: "Lunar Connection",
		classification: "Utilitarian",
		energyType: "Elemental",
		statRolled: "Power",
	},
	{
		number: 49,
		name: "Memory Manipulation",
		classification: "Manipulator",
		energyType: "Psychic",
		statRolled: "Manipulation",
	},
	{
		number: 50,
		name: "Meta Charisma",
		classification: "Manipulator",
		energyType: "Psychic",
		statRolled: "Manipulation",
	},
	{
		number: 51,
		name: "Meta Cognition",
		classification: "Clairvoyant",
		energyType: "Psychic",
		statRolled: "Consciousness",
	},
	{ number: 52, name: "Meta Constitution", classification: "Aegis", energyType: "Material", statRolled: "Endurance" },
	{ number: 53, name: "Meta Empathy", classification: "Manipulator", energyType: "Psychic", statRolled: "Awareness" },
	{
		number: 54,
		name: "Meta Evocation",
		classification: "Utilitarian",
		energyType: "Psychic",
		statRolled: "Consciousness",
	},
	{
		number: 55,
		name: "Meta Hearing",
		classification: "Clairvoyant",
		energyType: "Material",
		statRolled: "Perception",
	},
	{
		number: 56,
		name: "Meta Ingenuity",
		classification: "Animator",
		energyType: "Material",
		statRolled: "Creativity",
	},
	{
		number: 57,
		name: "Meta Intelligence",
		classification: "Utilitarian",
		energyType: "Psychic",
		statRolled: "Perception",
	},
	{ number: 58, name: "Meta Reflexes", classification: "Hammer", energyType: "Material", statRolled: "Reflexes" },
	{ number: 59, name: "Meta Smell", classification: "Clairvoyant", energyType: "Material", statRolled: "Awareness" },
	{ number: 60, name: "Meta Speed", classification: "Hammer", energyType: "Material", statRolled: "Reflexes" },
	{ number: 61, name: "Meta Strength", classification: "Hammer", energyType: "Material", statRolled: "Power" },
	{ number: 62, name: "Meta Taste", classification: "Clairvoyant", energyType: "Material", statRolled: "Awareness" },
	{ number: 63, name: "Meta Touch", classification: "Utilitarian", energyType: "Material", statRolled: "Reflexes" },
	{
		number: 64,
		name: "Meta Vision",
		classification: "Clairvoyant",
		energyType: "Material",
		statRolled: "Perception",
	},
	{ number: 65, name: "Meta Will", classification: "Aegis", energyType: "Psychic", statRolled: "Willpower" },
	{
		number: 66,
		name: "Mind Control",
		classification: "Manipulator",
		energyType: "Psychic",
		statRolled: "Manipulation",
	},
	{
		number: 67,
		name: "Mind Swap",
		classification: "Manipulator",
		energyType: "Psychic",
		statRolled: "Consciousness",
	},
	{
		number: 68,
		name: "Mirror Metapower",
		classification: "Arbiter",
		energyType: "Psychic",
		statRolled: "Manipulation",
	},
	{ number: 69, name: "Negate Metapower", classification: "Arbiter", energyType: "Cosmic", statRolled: "Awareness" },
	{
		number: 70,
		name: "Nether Projection",
		classification: "Cosmonaut",
		energyType: "Cosmic",
		statRolled: "Creativity",
	},
	{ number: 71, name: "Order Bending", classification: "Arbiter", energyType: "Cosmic", statRolled: "Consciousness" },
	{
		number: 72,
		name: "Pheromone Manipulation",
		classification: "Manipulator",
		energyType: "Elemental",
		statRolled: "Manipulation",
	},
	{ number: 73, name: "Planetary Powers", classification: "Hammer", energyType: "Elemental", statRolled: "Power" },
	{
		number: 74,
		name: "Portal Projection",
		classification: "Cosmonaut",
		energyType: "Cosmic",
		statRolled: "Perception",
	},
	{ number: 75, name: "Precognition", classification: "Clairvoyant", energyType: "Psychic", statRolled: "Awareness" },
	{ number: 76, name: "Pyrokinesis", classification: "Kineticist", energyType: "Elemental", statRolled: "Reflexes" },
	{
		number: 77,
		name: "Quantum Projection",
		classification: "Cosmonaut",
		energyType: "Cosmic",
		statRolled: "Perception",
	},
	{ number: 78, name: "Radiokinesis", classification: "Kineticist", energyType: "Cosmic", statRolled: "Willpower" },
	{ number: 79, name: "Random Metapower", classification: "Utilitarian", energyType: "Psychic", statRolled: "(Any)" },
	{ number: 80, name: "Reanimation", classification: "Animator", energyType: "Elemental", statRolled: "Creativity" },
	{ number: 81, name: "Regeneration", classification: "Aegis", energyType: "Elemental", statRolled: "Endurance" },
	{
		number: 82,
		name: "Retrocognition",
		classification: "Clairvoyant",
		energyType: "Psychic",
		statRolled: "Awareness",
	},
	{
		number: 83,
		name: "Seismokinesis",
		classification: "Kineticist",
		energyType: "Elemental",
		statRolled: "Endurance",
	},
	{ number: 84, name: "Shapeshift", classification: "Utilitarian", energyType: "Material", statRolled: "Endurance" },
	{ number: 85, name: "Singularity Powers", classification: "Hammer", energyType: "Cosmic", statRolled: "Power" },
	{ number: 86, name: "Sizeshift", classification: "Hammer", energyType: "Material", statRolled: "Power" },
	{ number: 87, name: "Solar Imitation", classification: "Aegis", energyType: "Elemental", statRolled: "Endurance" },
	{
		number: 88,
		name: "Spirit Manipulation",
		classification: "Manipulator",
		energyType: "Psychic",
		statRolled: "Manipulation",
	},
	{
		number: 89,
		name: "Substance Generation",
		classification: "Controller",
		energyType: "Elemental",
		statRolled: "Creativity",
	},
	{
		number: 90,
		name: "Substance Imitation",
		classification: "Aegis",
		energyType: "Material",
		statRolled: "Endurance",
	},
	{ number: 91, name: "Technopathy", classification: "Animator", energyType: "Psychic", statRolled: "Consciousness" },
	{ number: 92, name: "Telekinesis", classification: "Kineticist", energyType: "Psychic", statRolled: "Willpower" },
	{ number: 93, name: "Telepathy", classification: "Manipulator", energyType: "Psychic", statRolled: "Manipulation" },
	{ number: 94, name: "Teleport", classification: "Cosmonaut", energyType: "Cosmic", statRolled: "Perception" },
	{ number: 95, name: "Thermal Powers", classification: "Hammer", energyType: "Elemental", statRolled: "Power" },
	{ number: 96, name: "Time Bending", classification: "Arbiter", energyType: "Cosmic", statRolled: "Perception" },
	{
		number: 97,
		name: "Transfer Metapower",
		classification: "Arbiter",
		energyType: "Cosmic",
		statRolled: "Awareness",
	},
	{ number: 98, name: "Warp Reality", classification: "Arbiter", energyType: "Cosmic", statRolled: "Consciousness" },
	{ number: 99, name: "Weaken Metapower", classification: "Arbiter", energyType: "Cosmic", statRolled: "Awareness" },
	{ number: 100, name: "Zoopathy", classification: "Animator", energyType: "Elemental", statRolled: "Manipulation" },
];
