name: Metanthropes Automated Build & Release
on:
    push:
        branches:
            - main
jobs:
    build:
        name: Metanthropes Automated Builder
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the master branch
              uses: actions/checkout@v3
            - name: Get Product Name
              id: id
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: "system.json"
                  prop_path: "id"
            - name: Debug-print Product Name
              run: echo ${{steps.id.outputs.prop}}
            - name: Get Version Number
              id: version
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: "system.json"
                  prop_path: "version"
            - name: Debug-print Version Number
              run: echo ${{steps.version.outputs.prop}}
            - name: Set Download Link
              uses: jossef/action-set-json-field@v2
              with:
                  file: "./system.json"
                  field: "download"
                  value: "https://github.com/${{github.repository}}/releases/download/${{steps.version.outputs.prop}}/${{steps.id.outputs.prop}}.zip"
            - name: Pack Compendiums
              run: |
                  echo "Installing Foundry VTT CLI"
                  npm install -g @foundryvtt/foundryvtt-cli
                  echo "Contents of system/system"
                  dir /home/runner/work/${{steps.id.outputs.prop}}/${{steps.id.outputs.prop}}
                  echo "Create Data directory"
                  mkdir -p /home/runner/work/${{steps.id.outputs.prop}}/Data
                  echo "Contents of Data directory"
                  dir /home/runner/work/${{steps.id.outputs.prop}}/Data
                  echo "Configuring dataPath"
                  fvtt configure set dataPath "/home/runner/work/${{steps.id.outputs.prop}}/Data"
                  echo "Configure workon ${{steps.id.outputs.prop}} as a System"
                  fvtt package workon "${{steps.id.outputs.prop}}" --type "System"
                  echo "Packaging metapowers"
                  fvtt package pack -n "metapowers" --in ./src/packs/metapowers --out ./packs
                  echo "Packaging narrator-toolkit"
                  fvtt package pack -n "narrator-toolkit" --in ./src/packs/narrator-toolkit --out ./packs
                  echo "Packaging possessions"
                  fvtt package pack -n "possessions" --in ./src/packs/possessions --out ./packs
                  echo "Packaging premade-antagonists"
                  fvtt package pack -n "premade-antagonists" --in ./src/packs/premade-antagonists --out ./packs
                  echo "Packaging premade-protagonists"
                  fvtt package pack -n "premade-protagonists" --in ./src/packs/premade-protagonists --out ./packs
                  echo "Packaging rollable-tables"
                  fvtt package pack -n "rollable-tables" --in ./src/packs/rollable-tables --out ./packs
                  echo "Contents of Data directory post packaging"
                  dir /home/runner/work/${{steps.id.outputs.prop}}/Data
                  echo "Finished packaging Compendiums"
            - name: Zip the compiled files
              uses: thedoctor0/zip-release@0.7.1
              with:
                  type: "zip"
                  filename: "${{steps.id.outputs.prop}}.zip"
                  exclusions: "*.git* /*node_modules/* /*.vscode/* .npmignore .nvmrc gulpfile.js package-lock.json package.json /src/* /scss/* /sass/*"
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{steps.version.outputs.prop}}
                  name: ${{steps.id.outputs.prop}} - v${{steps.version.outputs.prop}}
                  generate_release_notes: true
                  draft: false
                  prerelease: false
                  files: |
                      ${{steps.id.outputs.prop}}.zip
                      system.json
