name: Metanthropes System Automated Build & Release
on:
    push:
        branches:
            - main
jobs:
    build:
        name: Metanthropes System Release Builder
        runs-on: ubuntu-latest
        steps:
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install SCSS Compiler
              run: npm install -g sass
            - name: Checkout the master branch
              uses: actions/checkout@v3
            - name: Get Product Name
              id: id
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: "system.json"
                  prop_path: "id"
            - name: Debug-print Product Name
              run: echo ${{steps.id.outputs.prop}}
            - name: Get Version Number
              id: version
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: "system.json"
                  prop_path: "version"
            - name: Debug-print Version Number
              run: echo ${{steps.version.outputs.prop}}
            - name: Set Download Link
              uses: jossef/action-set-json-field@v2
              with:
                  file: "./system.json"
                  field: "download"
                  value: "https://github.com/${{github.repository}}/releases/download/${{steps.version.outputs.prop}}/${{steps.id.outputs.prop}}.zip"
            - name: Pack Compendiums
              run: |
                  echo "Installing Foundry VTT CLI"
                  npm install -g @foundryvtt/foundryvtt-cli
                  echo "Contents of system/system"
                  dir /home/runner/work/${{steps.id.outputs.prop}}/${{steps.id.outputs.prop}}
                  echo "Create Data directory"
                  mkdir -p /home/runner/work/${{steps.id.outputs.prop}}/Data
                  echo "Contents of Data directory"
                  dir /home/runner/work/${{steps.id.outputs.prop}}/Data
                  echo "Configuring dataPath"
                  fvtt configure set dataPath "/home/runner/work/${{steps.id.outputs.prop}}/Data"
                  echo "Configure workon ${{steps.id.outputs.prop}} as a System"
                  fvtt package workon "${{steps.id.outputs.prop}}" --type "System"
                  echo "Packaging Demo-Actors"
                  fvtt package pack -n "demo-actors" --in ./src/packs/welcome --out ./packs
                  echo "Packaging Lobby"
                  fvtt package pack -n "lobby" --in ./src/packs/welcome --out ./packs
                  echo "Packaging System"
                  fvtt package pack -n "system" --in ./src/packs/system --out ./packs
                  echo "Packaging Welcome"
                  fvtt package pack -n "welcome" --in ./src/packs/welcome --out ./packs
                  echo "Packaging How-To-Play"
                  fvtt package pack -n "how-to-play" --in ./src/packs/welcome --out ./packs
                  echo "Packaging Hit Location Tables"
                  fvtt package pack -n "hit-location" --in ./src/packs/welcome --out ./packs
                  echo "Packaging System Toolkit"
                  fvtt package pack -n "toolkit" --in ./src/packs/toolkit --out ./packs
                  echo "Contents of Data directory post packaging"
                  dir /home/runner/work/${{steps.id.outputs.prop}}/Data
                  echo "Finished packaging Compendiums"
            - name: Compile SCSS to CSS
              run: |
                  sass scss/metanthropes.scss styles/metanthropes.css
                  sass scss/themes/theme-light.scss styles/metanthropes-light.css
                  sass scss/themes/theme-dark.scss styles/metanthropes-dark.css
            - name: Zip the compiled files
              uses: thedoctor0/zip-release@0.7.6
              with:
                  type: "zip"
                  filename: "${{steps.id.outputs.prop}}.zip"
                  exclusions: "*.git* /*node_modules/* /*.vscode/* *.npmignore *.nvmrc gulpfile.js package-lock.json package.json /src/* /scss/* /sass/* /*.cmd/* *.yaml *.d.ts"
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{steps.version.outputs.prop}}
                  name: ${{steps.id.outputs.prop}} - v${{steps.version.outputs.prop}}
                  generate_release_notes: true
                  draft: false
                  prerelease: false
                  files: |
                      ${{steps.id.outputs.prop}}.zip
                      system.json
